name: release-please

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
    outputs:
      release_created: ${{ steps.release.outputs['packages/catppuccin-tailwindcss--release_created'] }}
      tag_name: ${{ steps.release.outputs['packages/catppuccin-tailwindcss--tag_name'] }}

  release:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22
          registry-url: https://registry.npmjs.org
      - run: pnpm install --frozen-lockfile
      - run: pnpm publish
        working-directory: ./packages/catppuccin-tailwindcss
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
